### ISSUE TITLE
[auto-generated:1937561364] Unspecified error

### ISSUE THREAD

**Issue by Seiphon** [Seiphon/Intellij-error-handler#4]
This is a test!!!!!!

-----------------------------

- error.description: This is a test!!!!!!
- Plugin Name: Liferay IntelliJ Plugin
- Plugin Version: 1.2.0
- OS Name: Linux
- Java Version: 1.8.0_152-release
- Java VM Vendor: JetBrains s.r.o
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- App Version Name: IntelliJ IDEA
- Is EAP: false
- App Build: IU-183.4886.37
- App Version: 2018.3.2
- Last Action: EditorBackSpace

```
java.lang.RuntimeException: This is an artificial exception!
	at com.liferay.ide.idea.error.handler.TriggerExceptionAction.actionPerformed(TriggerExceptionAction.java:26)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:667)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:666)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:519)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:474)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:643)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Seiphon** [comment]
This is a test created at 2019.1.31 !!

-----------------------------

- error.description: This is a test created at 2019.1.31 !!
- Plugin Name: Liferay IntelliJ Plugin
- Plugin Version: 1.2.0
- OS Name: Linux
- Java Version: 1.8.0_152-release
- Java VM Vendor: JetBrains s.r.o
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- App Version Name: IntelliJ IDEA
- Is EAP: false
- App Build: IU-183.4886.37
- App Version: 2018.3.2
- Last Action: EditorBackSpace
